export { default as Head } from './Head'
export { default as Layout } from './Layout'
export { default as Loader } from './Loader'
export { default as Nav } from './Nav'
// export { default as Menu } from './menu'
// export { default as Side } from './side'
export { default as Social } from './Social'
export { default as Email } from './Email'
export { default as Footer } from './Footer'
export { default as Icon } from './Icon'
